---
# Area
- name: area/github
  color: "72ccf3"
  description: >-
    Changes made to github actions
- name: area/pre-commit
  color: "BC9BE3"
  description: >-
    Changes made to pre-commit hooks
- name: area/go
  color: "7BD7E0"
  description: >-
    Changes made to go resources
- name: area/docs
  color: "FBCA04"
  description: >-
    Changes made in the docs directory
- name: area/ttps
  color: "#c5def5"
  description: >-
    Changes made to go resources
# Renovate
- name: renovate/container
  color: "ffc300"
- name: renovate/github-action
  color: "ffc300"
- name: renovate/github-release
  color: "ffc300"
- name: renovate/helm
  color: "ffc300"
# Semantic Type
- name: type/digest
  color: "FFEC19"
- name: type/patch
  color: "FFEC19"
- name: type/minor
  color: "FF9800"
- name: type/major
  color: "F6412D"
- name: type/break
  color: "F6412D"
# Release Issue
- name: image-not-found
  color: "ee0701"
# Uncategorized
- name: bug
  color: "ee0701"
- name: do-not-merge
  color: "ee0701"
- name: docs
  color: "F4D1B7"
- name: enhancement
  color: "84b6eb"
- name: broken-links
  color: "7B55D7"
- name: question
  color: "cc317c"
- name: community
  color: "0e8a16"
