---
builds:
  - id: "ttpforge"
    binary: ttpforge

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm
      - arm64

    # GOARM to build for when GOARCH is arm.
    goarm:
      - 6
      - 7

    # GOAMD64 to build when GOARCH is amd64.
    goamd64:
      - v2
      - v3
