---
api_version: 2.0
uuid: 763a6408-d395-4737-92ba-4b8bb20b7976
name: Default Cleanup Actions Demo
authors:
  - meta
description: |
  Certain types of actions, such as `create_file`, have a default cleanup
  action that you can enable by specifying `cleanup: default` in the relevant
  step. This TTP shows how the `create_file` default cleanup action deletes
  the created file.
steps:
  - name: create_file_cleanup_demo
    create_file: /tmp/ttpforge-default-cleanup-demo-{{randAlphaNum 10}}
    contents: this will be automatically deleted...
    cleanup: default
