---
name: "Meta Labeler"
on:
  pull_request_target:

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Labeler
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Labeler
        uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4.3.0
        with:
          configuration-path: .github/labeler.yaml
          repo-token: "${{ secrets.BOT_TOKEN }}"
