---
name: "Meta Labeler"
on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@0776a679364a9a16110aac8d0f40f5e11009e327 # v4.0.4
        with:
          configuration-path: .github/labeler.yaml
          repo-token: "${{ secrets.BOT_TOKEN }}"
