---
name: "Meta Labeler"
on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@ba790c862c380240c6d5e7427be5ace9a05c754b # v4.0.3
        with:
          configuration-path: .github/labeler.yaml
          repo-token: "${{ secrets.BOT_TOKEN }}"
